import img3 from "../../image/anime/slideimg.jpg";
import cover from "../../image/anime/cover.jpg";
export const data = [
  {
    title: "Anime1",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime2",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime3",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime4",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime5",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
  {
    title: "Anime6",
    banner: img3,
    cover: cover,
    decs: "Entertainment community sharing source and architectural formula",
    star: "9.4",
    year: "2022",
    chapter: "24",
    type: ["Action", "Drama", "Fantasy", "Supper Power"],
    path: "/",
  },
];
